/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.JOptionPane;

/**
 *
 * @author Danish
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        newMemberMenu = new javax.swing.JMenu();
        updateAndDeleteMenu = new javax.swing.JMenu();
        listOfMembersMenu = new javax.swing.JMenu();
        paymentMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1000));
        setMinimumSize(new java.awt.Dimension(2000, 1000));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(2000, 1000));

        jPanel1.setBackground(new java.awt.Color(0, 118, 221));
        jPanel1.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(2000, 1000));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym-logos-colour-200.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addContainerGap(868, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        newMemberMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new member.png"))); // NOI18N
        newMemberMenu.setText("New Member");
        newMemberMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        newMemberMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newMemberMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(newMemberMenu);

        updateAndDeleteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update & delete member.png"))); // NOI18N
        updateAndDeleteMenu.setText("Update & Delete");
        updateAndDeleteMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateAndDeleteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateAndDeleteMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(updateAndDeleteMenu);

        listOfMembersMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list of members.png"))); // NOI18N
        listOfMembersMenu.setText("List of Members");
        listOfMembersMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listOfMembersMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOfMembersMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(listOfMembersMenu);

        paymentMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment.png"))); // NOI18N
        paymentMenu.setText("Payment");
        paymentMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(paymentMenu);

        logoutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutMenu.setText("Logout");
        logoutMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutMenu);

        exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        exitMenu.setText("Exit");
        exitMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Logout Application","Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a==0)
        {
            setVisible(false);
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Exit Application","Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a==0)
        {
           System.exit(0);
        }
    }//GEN-LAST:event_exitMenuMouseClicked

    private void newMemberMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMemberMenuMouseClicked
        setVisible(false);
        new NewMember().setVisible(true);
    }//GEN-LAST:event_newMemberMenuMouseClicked

    private void updateAndDeleteMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateAndDeleteMenuMouseClicked
        setVisible(false);
        new UpdateAndDelete().setVisible(true);
    }//GEN-LAST:event_updateAndDeleteMenuMouseClicked

    private void listOfMembersMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOfMembersMenuMouseClicked
        setVisible(false);
        new ListOfMembers().setVisible(true);        
    }//GEN-LAST:event_listOfMembersMenuMouseClicked

    private void paymentMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentMenuMouseClicked
        setVisible(false);
        new Payment().setVisible(true); 
    }//GEN-LAST:event_paymentMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu exitMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu listOfMembersMenu;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenu newMemberMenu;
    private javax.swing.JMenu paymentMenu;
    private javax.swing.JMenu updateAndDeleteMenu;
    // End of variables declaration//GEN-END:variables
}
