/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Danish
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        incorrectLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        incorrectLabel = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        usernameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        backgroundPicLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 30));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 221));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, -1));

        incorrectLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incorrectLabel.setForeground(new java.awt.Color(255, 0, 0));
        incorrectLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        incorrectLabel.setText("Username or password is incorrect");
        getContentPane().add(incorrectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, -1));

        passwordPasswordField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordPasswordField.setForeground(new java.awt.Color(0, 118, 221));
        passwordPasswordField.setText("Enter Password");
        passwordPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordPasswordFieldFocusLost(evt);
            }
        });
        getContentPane().add(passwordPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 282, 36));

        usernameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(0, 118, 221));
        usernameTextField.setText("Enter Username");
        usernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 282, 36));

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 118, 221));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        showPasswordCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showPasswordCheckBox.setForeground(new java.awt.Color(0, 118, 221));
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, -1, -1));

        backgroundPicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login background.PNG"))); // NOI18N
        getContentPane().add(backgroundPicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusGained
        incorrectLabel.setVisible(false);
        if(usernameTextField.getText().equals("Enter Username"))
        {
            usernameTextField.setText("");
            usernameTextField.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_usernameTextFieldFocusGained

    private void usernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusLost
         incorrectLabel.setVisible(false);
        if(usernameTextField.getText().equals(""))
        {
            usernameTextField.setText("Enter Username");
            usernameTextField.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_usernameTextFieldFocusLost

    private void passwordPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPasswordFieldFocusGained
        incorrectLabel.setVisible(false);
        if(passwordPasswordField.getText().equals("Enter Password"))
        {
            passwordPasswordField.setText("");
            passwordPasswordField.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_passwordPasswordFieldFocusGained

    private void passwordPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPasswordFieldFocusLost
        incorrectLabel.setVisible(false);
        if(passwordPasswordField.getText().equals(""))
        {
            passwordPasswordField.setText("Enter Password");
            passwordPasswordField.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_passwordPasswordFieldFocusLost

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Exit Application","Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(usernameTextField.getText().equals("express") && passwordPasswordField.getText().equals("1234"))
        {
            setVisible(false);
            new Home().setVisible(true);
        }
        else
            incorrectLabel.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if(showPasswordCheckBox.isSelected())
        {
            passwordPasswordField.setEchoChar((char)0);
        }
        else
            passwordPasswordField.setEchoChar('*');
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPicLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel incorrectLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
